### ISSUE TITLE
Download links are broken for latest release

### ISSUE THREAD

**Issue by lol768** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1143]
Link given [here](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/releases/tag/v1.9.0) is:

```
https://storage.googleapis.com/***/v1.9.0/mysql-socket-factory-1.9.0-jar-with-driver-and-dependencies.jar
```

returns HTTP 400 with XML body:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<Error>
  <Code>InvalidBucketName</Code>
  <Message>The specified bucket is not valid.</Message>
  <Details>Invalid bucket name: '***'</Details>
</Error>
```

The link _should_ be 

```
https://storage.googleapis.com/cloud-sql-connectors-java/v1.9.0/mysql-socket-factory-1.9.0-jar-with-driver-and-dependencies.jar
```

I'm not sure if the commit here https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/commit/8ab2707fa2ef760350dc3efecc5eeeb5825d0c6b by @shubha-rajan fixes this - but the release should've been deleted and the action re-run if so, as the links are all currently useless

**Comment by shubha-rajan** [comment]
Updated the release! The automation should be fixed now. That was a manual error actually. In the last release, the job failed to update the release notes, so I copied them manually from the logs and missed that the bucket names were obfuscated. It shouldn't happen next time, since the release automation should work. We're still in the process of transitioning from a manual to an automated release process so please forgive the hiccups!
