### ISSUE TITLE
How to connect to load-balanced read replicas?

### ISSUE THREAD

**Issue by gaurav517** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1453]
### Question

As suggested in some docs from Google, we are using HAProxy to load balance cloudsql replicas. Would it be possible to use this library for IAM authentication? If yes, what would be the `cloudSqlInstance` in connection string? 

Thanks

**Comment by hessjcg** [comment]
Hi @gaurav517. 

You will not be able to use the JDBC Socket Factory with a group of load-balanced cloud-sql replicas. The JDBC Socket Factory always connects to the IP Address of the Cloud SQL instance read from the Cloud SQL API. There is no way to direct the JDBC Socket Factory to connect to an alternate IP Address.

**Comment by enocom** [comment]
For reference, I assume this is the design:

https://cloud.google.com/blog/products/databases/using-haproxy-to-scale-read-only-workloads-on-cloud-sql-for-postgresql

**Comment by enocom** [comment]
It is possible to leverage automatic IAM authentication without the connector while using HAProxy, though. I can elaborate if there's interest.

**Comment by gaurav517** [comment]
Yes.. Because we can't use socket factory for client side load balancing, now we are looking for solutions to use IAM authentication with HAProxy loadbalanced MySQL replicas. We are using the design that you commented earlier.
It would be great to get your ideas.
Thanks.

**Comment by enocom** [comment]
So high level, the Connector is valuable for two big reasons:

1. As a path around authorized networks when connecting to public IP
2. As a way to enable Auto IAM Authentication (where the Connector refreshes the token for you so that your connection pool can always connect with a fresh OAuth2 token).

For our case here point 1 is orthogonal and in any case, I'd recommend using private IP anyway. For point 2, it's actually pretty easy to enable OAuth2 token refresh without the Connector and just a little know-how with HikariCP.

Here's the idea:

Instead of using the Connector, you configure HikariCP as if you were just connecting directly. Then you do this:

``` java
import com.google.auth.oauth2.AccessToken;
import com.google.auth.oauth2.GoogleCredentials;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import java.io.IOException;

public class CloudSqlAutoIamAuthnDataSource extends HikariDataSource {

  public CloudSqlAutoIamAuthnDataSource(HikariConfig configuration) {
    super(configuration);
  }

  @Override
  public String getPassword() {
    GoogleCredentials credentials;
    try {
      credentials = GoogleCredentials.getApplicationDefault();
    } catch (IOException err) {
      throw new RuntimeException(
          "Unable to obtain credentials to communicate with the Cloud SQL API", err);
    }

    // Scope the token to ensure it's scoped to logins only.
    GoogleCredentials scoped = credentials.createScoped(
        "https://www.googleapis.com/auth/sqlservice.login");

    try {
      scoped.refresh();
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
    AccessToken accessToken = scoped.getAccessToken();
    return accessToken.getTokenValue();
  }
}
```

Wherever you're creating your DataSource, you'd use the CloudSqlAutoIamAuthnDataSource instead. And that's it. Now you can connect directly to your instance (or HAProxy) IP address and still get the equivalent of Auto IAM Authentication.

Note: depending on your use case you might want to adjust how you fetch the token. Above I've shown how to do it with Application Default Credentials, which should cover you 90% of the time.

**Comment by enocom** [comment]
Yes, same idea for MySQL. This is at the layer of JDBC, so it's agnostic to the underlying database engine.

> I understand this snippet is just an idea.. but how would you refresh the token before that expires?

This actually works just fine. Every time the connection pool closes a stale connection and re-creates a new one, it calls the overridden getPassword function which fetches a fresh token. In theory you could introduce caching here, but generally the token retrieval is fast.

> Would a refresh of token (password change) create new connections? (won't reuse existing connection?)

The answer here is the same as above. It helps to think about how HikariCP works a bit to understand why. Basically, on startup, Hikari opens X number of connections with the credentials you provide. Since we've made getPassword fetch an OAuth2 token, the initial connections will use this token. After some time period (~30 min by default I think), Hikari will start closing inactive connections, and re-open new ones. Again, it will use the getPassword method we've provided and will fetch a fresh OAuth2 token to create new connections.

So all in all, it's pretty simple.

**Comment by gaurav517** [comment]
hmm okay. I need to look deeper into how Hikari connection handling works but would it be safe to assume that each connection in the pool will use its own distinct access token and a connection is guaranteed to refresh within an hour after creation?

We are also assuming that `scoped.refresh();` would fetch a new token every time, regardless of expiry time. I found it to be true when running the code locally but strangely in GKE environment it behaves differently.. it returns previous valid token (same value/expiry) until about 5 mins before expiry.. I am using same service account and same code.. With this behaviour, it won't work in GKE right? I am trying to look deeper.. let me know if you get some ideas.

Thanks a lot.

**Comment by enocom** [comment]
>  I need to look deeper into how Hikari connection handling works but would it be safe to assume that each connection in the pool will use its own distinct access token and a connection is guaranteed to refresh within an hour after creation?

Definitely. Every new connection gets a fresh OAuth2 token. Existing connections are unaffected.

> While testing this with only access token I found it to be true when running the code locally but strangely in GKE environment it behaves differently.. it returns previous valid token (same value/expiry) until about 5 mins before expiry

GKE runs a metadata server that provides tokens. That server caches OAuth2 tokens and refreshes them at the ~5 min to expiration mark. The Connection pool does not take 5 minutes to connect (it's probably a few seconds tops) so you'll be fine here.

**Comment by gaurav517** [comment]
Trying to think loud to find a breaking scenario. 

Assuming we have a connection pool with two connections.

T+0:
connection-1: token-A (time to expire: 60)
connection-2: token-A (because of GKE caching, time to expire: 60)

T+t1: connection-2 gets cleaned up and connection-3 is created.
connection-1: token-A (time to expire: 60-t1)
connection-3: token-A (time to expire: 60-t1)

T+t2: connection-1 gets cleaned up and connection-4 is created.
connection-3: token-A (time to expire 60-t2)
connection-4: token-A (time to expire 60-t2)

T+t3 (Assuming 60-t3 < 5 mins): connection-3 gets cleaned up and connection-5 is created. 
connection-4: token-A (time to expire 60-t3)
connection-5: token-B (time to expire T+t3+60)

So although connection-4 used token-A that won't be valid after 60-t3 (< 2 mins), but session is authenticated for the lifetime of the connection-4.. assuming auth only happens while creating a connection and there is no re-authentication after a connection is already created. Is my assumption correct here?

Thanks,
Kumar

**Comment by enocom** [comment]
> So although connection-4's token-A won't be valid after 60-t3 (< 5 mins), but session is authenticated for the lifetime of the connection-4.. assuming auth only happens while creating a connection and there is no re-authentication after a connection is already created. Is my assumption correct here?

Yes completely correct. Tokens are used only to create the session. And in any case, the Java Connector works no differently -- it retrieves a token at connection creation time. The code above is merely demonstrating how to do all this without the Connector.

Note: the Connector's single responsibility is creating automated mTLS connections. If mTLS isn't a critical need and standard TLS is adequate, then you're good to go with the above.

I'm going to close this, but feel free to re-open if there are more things to cover here.
