### ISSUE TITLE
Investigate how to integrate w/ r2dbc driver

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#164]
r2dbc driver can connect to PostgreSQL.  CloudSQL user opened an issue with use case to use r2dbc to connect to CloudSQL PostgreSQL.

https://github.com/spring-projects/spring-data-r2dbc/issues/192

r2dbc cannot accept a Socket since it's Netty based. However, it has been updated to be able to accept a `TrustManager` and `KeystoreManager`.

Propose that:
1. We can expose the factory for both of these objects, so that we can use out of the box r2dbc immediately.
1. Or, create our own `ConnectionFactory` so that we can wrap both drivers and configure them with SSL.
1. Investigate adding r2dbc driver specifically for CloudSQL PostgreSQL.

/cc @kurtisvg @meltsufin @elefeint

**Comment by masoudparvari** [comment]
Hi @saturnism, any update or timeline on this? Publishing of r2dbc-postgresql 0.8.0.RELEASE is imminent and it will support Unix Domain Socket. So I am wondering from within a gcp app which already can connect to the gcp postgres with jdbc driver and through spring cloud gcp autoconfigure with providing "instance-connection-name" and datasource username/password, is it possible to replace jdbc with r2dbc and unix socket "/cloudsql/INSTANCE_CONNECTION_NAME/.s.PGSQL.5432." ?
Honestly this has stopped us from taking R2DBC into production.

**Comment by meltsufin** [comment]
cc/ @elefeint

**Comment by saturnism** [comment]
/cc @kurtisvg 

@masoudparvari  btw - which environment are you connecting from? App Engine, or somewhere else?

Thanks!

**Comment by masoudparvari** [comment]
@saturnism from within a kubernetes pod (app) in GCE and google cloud postgres database resides within the same cluster

**Comment by saturnism** [comment]
@masoudparvari The only work around I can think of right now is to use the Cloud SQL proxy as a side car, and expose a shared unix socket domain in a shared volume within the pod.   In which case, r2dbc driver should be able to connect to this unix socket domain file directly and no additional cert is needed.  It's not as simple as Spring Cloud GCP, but it should work. Would you be interested in giving that a try?

**Comment by kurtisvg** [comment]
I don't currently have any plans for R2DBC support on the roadmap. I'm not overly familiar with this project - can anyone provide some additional context on why this is important and what benefits this has over the currently supported drivers?

@masoudparvari If your only goal is to run on k8s, you can use the [Cloud SQL proxy in as a sidecar](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine) in your pod. The proxy can provide either a TCP socket or a Unix domain socket. 

Unix domain sockets are currently only required when connecting from GAE-Standard, Cloud Functions, or Cloud Run.

**Comment by masoudparvari** [comment]
@saturnism yeah but in my case Cloud SQL Proxy is not an option. I was more looking for a seamless tcp socket connecting way like project "cloud-spanner-r2dbc"

@kurtisvg In a reactive non-blocking architecture, which scales very good and requires way less resources, R2DBC provides non blocking access to database so you do not need to block the requester thread and you free the thread for other tasks and as soon as there is a response from database, we receive a call back. R2DBC is netty based which is de facto framework for asynchronous non blocking communication over network and now database. As whole Java community is embracing reactive evolution, I think an integration of google cloud sql with R2dbc absolutely is worth the effort.

**Comment by kurtisvg** [comment]
@masoudparvari Is there a particular reason the Cloud SQL proxy isn't an option? The Cloud SQL proxy creates connections in the exact same way as this library - the only difference is the SF is process-naive, while the proxy requires an external process.

**Comment by saturnism** [comment]
@kurtisvg to be clear, there shouldn't be any work that needs to be done directly on r2dbc. We simply need to expose some of the APIs to expose some logic to get the cert directly as oppose to the pre-configured ssl socket factory.  r2dbc lead already exposes some hooks for us to plugin the cert. i'm planning to take a look.

**Comment by kurtisvg** [comment]
I'm not quite sure that it'll be possible to just expose the certs, and the connection factory also handles somewhat complex logic on when to renew.  

Not sure if it's possible to provide a "Connection Factory" that can create the initial connection on behalf of the driver similar to the existing mechanisms, but that would be preferred (and probably more sustainable).

**Comment by mp911de** [comment]
You should be able to keep your renewal as the only thing that gets exchanged is the SSLCintext right now. Existing connections remain unaffected once the SSL handshake is done. 

The R2DBC Postgres driver requires a callback function that is called upon connect and that needs access to the certificate objects that are valid at the time of connect, basically the same scheme as with JDBC drivers.

**Comment by mp911de** [comment]
Is there anything we can help with from an R2DBC Postgres or MySQL server perspective?

**Comment by kurtisvg** [comment]
Ideally, providing a "SocketFactory" interface and a way to specify which socketFactory the driver would use to create connections be the best option from my perspective. This would allow us to match the current pattern and just implement that interface around our CoreConnectionFactory. 

Right now, it sounds like we would need to provide something that wraps around the R2DBC driver call so we can configure the IP address and SSLContext from in the instance connection name.

**Comment by mp911de** [comment]
`SocketFactory` is part of blocking I/O. R2DBC drivers use netty which does not use plain `Sockets` but rather a non-blocking abstraction above sockets. So the `SocketFactory` pattern isn't applicable to netty. 

However, the SSL handler still works with using a `KeyManager` and a `TrustManager`. IIRC, @saturnism had a tiny implementation prepared that demoed how to integrate with R2DBC drivers.

Looking at the code, `CloudSqlInstance`/`InstanceData` would be required to keep and expose references to `KeyManager` and a `TrustManager` that are used to build the `SSLContext`.

**Comment by kurtisvg** [comment]
> `SocketFactory` is part of blocking I/O. R2DBC drivers use netty which does not use plain `Sockets` but rather a non-blocking abstraction above sockets. So the `SocketFactory` pattern isn't applicable to netty.

I'm unfamiliar with the intricacies of netty, so forgive me if I'm missing something obvious. Why can't the driver accept an argument for a "SocketFactory" that provides the non-blocking abstraction over the socket (instead of a literal `SocketObject`)? 

My understanding of the RD2BCs pattern is that the user would call connect (specifying the IP and the callback function) after the initial "connection" is dialed the callback is used to perform the SSL configuration. Is this correct? So the user would need to know the IP address (or we would need to provide a function for the user to access it prior to calling connect). 

With the `SocketFactory` pattern, the user only needs to specify their `instance_connection_name` and the socketFactory to the driver, and we derive the instance's IP and dial the connection from inside the socketFactory. Not only does this mean less configuration for the user, but it potentially leaves the door open for features like interacting with driver support for the read replicas semi-automatically.

Additionally, it's unclear to me if the callback function provides feedback in case of Exceptions. The current pattern lets us trigger retries when `connect` throws exceptions, in case something has happened (like an instance failover) and the SSL information is outdated.

**Comment by mp911de** [comment]
> I'm unfamiliar with the intricacies of netty, so forgive me if I'm missing something obvious. Why can't the driver accept an argument for a "SocketFactory" that provides the non-blocking abstraction over the socket (instead of a literal SocketObject)?

No worries. Happy to help. There are two reasons why this isn't possible:

1. `SocketFactory` is part of the blocking API meaning each time a connection is dialed or each time the SSL handshake happens, the user thread is blocked. That is why we cannot use these facilities. You cannot turn a blocking API into a non-blocking one. If it blocks, then we cannot do anything about it.
2. Netty uses its own abstraction for socket creation as the underlying sockets can be non-standard Java sockets (e.g. kqueue or epoll TCP sockets).

> My understanding of the RD2BCs pattern is that the user would call connect (specifying the IP and the callback function) after the initial "connection" is dialed the callback is used to perform the SSL configuration. Is this correct? So the user would need to know the IP address (or we would need to provide a function for the user to access it prior to calling connect).

Exactly. The Postgres driver already exposes the callback function to obtain/configure the SSL context when dialing the connection. The MySQL needs to implement this callback (paging @mirromutth). The SSL callbacks are driver-specific.

R2DBC provides as part of the SPI a `ConnectionFactoryProvider` that can configure the driver (`ConnectionFactory`) along with the IP address/unix domain socket. That would be the only R2DBC-specific component that needs to be implemented by this project to resolve the IP address. A user gets a fully configured `ConnectionFactory` in return and is not required to provide additional options.

That being said, hooking into `ConnectionFactoryProvider` allows you as well to configure read replicas as soon as the R2DBC Postgres driver supports master/slave configuration.

> Additionally, it's unclear to me if the callback function provides feedback in case of Exceptions. The current pattern lets us trigger retries when connect throws exceptions, in case something has happened (like an instance failover) and the SSL information is outdated.

Yes, it does. If SSL information are outdated, then the connection creation fails along with a proper exception cause. If we wanted to add retry behavior, we would need to implement a `ConnectionFactory` facade that uses a conditional retry operator that attempts one or two retries (depending on what we want/configure) if the connect fails because of an outdated SSL config.

**Comment by kurtisvg** [comment]
Ah okay, it sounds like `ConnectionFactoryProvider` is the hook I was looking for. I'll reach out to @saturnism to see what he has so far and see if we can add support during the next quarter.

**Comment by meltsufin** [comment]
@kurtisvg Please loop my team in as well. We might have some cycles to work on this next quarter as well. Thanks!

**Comment by PedroAlvarado** [comment]
I'm a new GCP customer and I was hoping to use R2DBC(from Cloud Run) with Cloud SQL. In my attempt to set things up I ran into this ticket. Are the changes proposed in this issue still planned?

**Comment by kurtisvg** [comment]
@PedroAlvarado - Yes, these changes are still planned. I intended to have them complete this quarter, but with the state of the world both priorities has shifted and velocity has slowed and I wasn't able to get to it.

**Comment by PedroAlvarado** [comment]
Thank you for your quick response @kurtisvg. Do you have a rough timeline for when this change(or branch at least) will be available? We are looking to decide whether we abandon this path or wait for this change to come through.

**Comment by kurtisvg** [comment]
Roughly, anywhere between 1-3 months (it'll be on our goals for next quarter).

**Comment by dmitry-s** [comment]
Hi @PedroAlvarado,

Yes it is planned. I'm going to start working on it this week.

Thanks!
