### ISSUE TITLE
Fat "jar-with-dependencies" PostgreSQL JDBC driver is missing Guava dependency inside

### ISSUE THREAD

**Issue by Tasssadar** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1858]
### Bug Description

I've built the JDBC postgres socket factory with `mvn -P jar-with-dependencies clean package -DskipTest` as pre README. 

When trying to use the `postgres-socket-factory-1.16.1-SNAPSHOT-jar-with-dependencies.jar`, I get this runtime failure:
```
ERROR: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/internal/InternalFutureFailureAccess
```

When I remove `<scope>test</scope>` from Guava entry in `jdbc/postgres/pom.xml`, the resulting JAR file works. I'm however not sure if that is the right fix or if the Guava omission is not intentional, so I didn't create a PR.

### Steps to reproduce?

1. Build with `mvn -P jar-with-dependencies clean package -DskipTest`
2. Use in some project with JDBC driver that is not already using Guava, eg. Keycloak
3. Runtime error with not found class

### Environment

1. OS type and version: Linux
2. Java SDK version: 17
3. Cloud SQL Java Socket Factory version: 1.16.1

**Comment by ttosta-google** [comment]
Thanks @Tasssadar for opening this issue!

The solution is to remove the `com.google.guava` dependency from the `jdbc/postgres/pom.xml` as it is not used in this module (only by `jdbc-socket-factory-core`). Adding `test` scope blocks the dependency from being added to the `jar`.

Would you like to put up a PR for this fix and update file `jdbc/postgres/pom.xml`? Otherwise I can happily do it.

**Comment by Tasssadar** [comment]
Thanks for the quick response! Created #1861 , also removing it from the other drivers that had it as `<scope>test</scope>`.

**Comment by ttosta-google** [comment]
Thank you @Tasssadar ! PR merged.
