### ISSUE TITLE
Update UserAgent format for usage metrics

### ISSUE THREAD

**Issue by jsimonweb** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#219]
UserAgent should be in the format of "[tool-name]/[version]"

For example:

USER_AGENT_PROPERTY_NAME = "mysql-socket-factory-connector-j-8/1.0.15";

**Comment by kurtisvg** [comment]
1. We need to update the application name to `cloud-sql-java-connector/$VERSION`, which is set here: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/919084f7bb9aaf22bef5d20a13fd3d85fd69d083/core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java#L341-L347

We also need to set this in a way that is compatible with Spring folks (and other third party tools), who currently override. @jsimonweb suggested that we just manual insert a space, so that other names are set like `"mysql-socket-factory-connector-j-8/1.0.15 $CUSTOM_NAME"`. Spring usage: https://github.com/spring-cloud/spring-cloud-gcp/blob/8850186d11d9604ac1ce771a5313389306fa3350/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/sql/GcpCloudSqlAutoConfiguration.java#L173-L174
