### ISSUE TITLE
[Feature request] Improve feedback messages when refreshing Cloud SQL instance credentials

### ISSUE THREAD

**Issue by gcp-grauj** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#502]
## Feature Description

- Currently, to connect to Cloud SQL instances, the Admin API [1] is used to create an ephemeral SSL certificate for the authentication
- On certain scenarios, retrieving this certificate may fail, raising exceptions similar to the following:
```
java.lang.RuntimeException: Failed to update metadata for Cloud SQL instance. at 
  com.google.cloud.sql.core.CloudSqlInstance.addExceptionContext(CloudSqlInstance.java:455)
  at com.google.cloud.sql.core.CloudSqlInstance.fetchMetadata(CloudSqlInstance.java:322) 
```
- Although these exceptions are expected, have no impact on the code execution, and later retries succeed, raising these messages as exceptions may be disruptive on cases where these errors are transient
- Providing additional context on why these exceptions are raised [2] , and what they mean, would improve the experience when using these libraries

## Request
- Can we make it more clear what are these exceptions, and differentiate cases where these are transient and resolved with just a retry, to cases where these could be more disruptive? 

## Additional Context
[1] https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/sslCerts/createEphemeral
[2] https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/5ceacadbca5d91018b53a8131f3b5b110d70155d/core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java#L345
[3] https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/267
[4] https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/310

**Comment by kurtisvg** [comment]
> Although these exceptions are expected, have no impact on the code execution

This is not true. These exceptions are not expected (they indicate that a refresh operation has failed), and do change code execution (a new refresh is triggered earlier than planned).

> and later retries succeed, raising these messages as exceptions may be disruptive on cases where these errors are transient

Even when the exceptions are transient, they are only raised when it has impacted a connection attempt. It's impossible for the library to determine if an error is transient or not. Raising the exception indicates that this attempt failed for a specific reason.

**Comment by gcp-grauj** [comment]
I agree with you that the expected behaviour is that the credential refresh operations should be successful, to clarify I meant that these exceptions are raised then the operations automatically retried, as it's expected that a failed credential refresh can happen (without taking into account the cause of the exception), and can be resolved with a retry. 

On the code execution part, as these libraries are used as dependencies for other libraries, although these exceptions are raised, they often don't impact the application's execution, as the credential refresh is automatically retried and often successful.

I also agree that it's not possible to know why these exceptions are transient or not without knowing what is the cause of them. But when the operation succeeds after a retry, we know that the error was transient. Why aren't these exceptions raised after an exponential backoff + retry operation fails instead? Still, this FR is to improve the feedback of this error message, and make it more clear that these exceptions are retried in the background, and don't necessarily indicate an issue

**Comment by kurtisvg** [comment]
> Why aren't these exceptions raised after an exponential backoff + retry operation fails instead?

Essentially because the refresh operation is a (relatively) long network operation, which is blocking another network operation (connecting to the instance). Every users particular sensitivity to a blocking operation is going to be different, so there is an infinite amount of variability in how to handle this. Is 3 retries acceptable? How about 5? 10? Now all of the sudden you're waiting 10-20s for these requests (and their back off to complete) before letting the user know that something went wrong. This gets particularly complicated because connection poolers almost always have a retry strategy baked in as well. So now we have bunch of nested retry logic, which may conflict - specifically in the case which we are still retrying for a successful attempt. 

So instead, we've chosen the strategy that limits each connection attempt to blocking on a single refresh operation. Most of the time we expect a refresh operation to be complete before the user needs it (we start refreshing ~5 minutes before the old value expires) and a single failure shouldn't be surfaced. The exception to this is that if you are running in an environment that throttles background activity (Cloud Run / Cloud Functions / etc), you may get unlucky and have your certs expire between the refresh is possible.

**Comment by kurtisvg** [comment]
Marking this as closed. While the top level error (failed to update metadata) isn't helpful, the cause of that error is also included and should give a better description as to why the refresh failed.

**Comment by maguro** [comment]
> The exception to this is that if you are running in an environment that throttles background activity (Cloud Run / Cloud Functions / etc), you may get unlucky and have your certs expire between the refresh is possible.

jfyi, this is happening to us and is continually generating incident reports. :(

**Comment by enocom** [comment]
@maguro Are you using the latest version? https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/561 should have limited the refresh problem in Cloud Run (for the most part).

**Comment by maguro** [comment]
@enocom We're using v1.4.2 and are still having these "spurious" error messages.

**Comment by enocom** [comment]
@maguro Mind opening a new issue, describing your setup and more details of what you're seeing?
